### Mis expectativas del curso son las siguientes:
Tal cual como lo leí en la tarea 1, mis expectativas son similaras a las que venian en dicho texto,
- <font color = red> DESARROLLAR PROCESOS DE SIMULACIÓN QUE AYUDEN A GENERAR VALOR </font>
- Aprender tecnicas para simular.
- Aprender a como desarrollar un proyecto de simulación para estados financieros o de sistemas económicos.
- Desarrollar mi destreza para programar.
- Detectar las variables más importantes de un sistema a través de un proyecto de simulación.
- Resolver problemás con ayuda de calculos $$ \partial x $$ $$ \int_{-a}^{b} e^x\, dx $$











Write a Python program to convert a list of numeric value into a one-dimensional
NumPy array. Expected Output:
Original List: [12.23, 13.32, 100, 36.32]
One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [34]:
import numpy as np
a = [27.01, 8, 9.0]
m = np.array(a)
print(a)
print("Respuesta\n",m)

[27.01, 8, 9.0]
Respuesta
 [ 27.01   8.     9.  ]


Write a Python program to create a null vector of size 10 and update sixth value to 11.

In [35]:
a = np.zeros(10)
a[6] = 11
print("Respuesta\n",a)

Respuesta
 [  0.   0.   0.   0.   0.   0.  11.   0.   0.   0.]


Write a Python program to create a array with values ranging from 12 to 38.

In [36]:
a = np.arange(12,38)
print ("Respuesta\n",a)

Respuesta
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36
 37]


In [ ]:
Write a Python program to reverse an array (first element becomes last)

In [37]:
a = np.arange(0,10)
a=a[::-1]
print ("Respuesta\n",a)

Respuesta
 [9 8 7 6 5 4 3 2 1 0]


Write a Python program to create a 2d array with 1 on the border and 0 inside.


In [38]:
a=np.ones((5,5))
print(a,"\n")
a[1:-1,1:-1] = 0
print("Respuesta\n",a)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]] 

Respuesta
 [[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


Write a Python program to add a border (filled with 0’s) around an existing array

In [39]:
a = np.ones((3,3))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print("Respuesta\n",a)

Respuesta
 [[ 0.  0.  0.  0.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  1.  1.  1.  0.]
 [ 0.  0.  0.  0.  0.]]


Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern

In [40]:
a = np.ones((3,3))
a = np.zeros((8,8),dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1


Respuesta
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 Write a Python program to convert the values of Centigrade degrees into Fahrenheit
degrees. Centigrade values are stored into a NumPy array.
Sample Array [0, 12, 45.21 ,34, 99.91]
Expected Output:
Values in Fahrenheit degrees: [0.0 12.0 45.21 34.0 99.91]
Values in Centigrade degrees: [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778].
Use functions and list comprehension read the link https: // www. pythonforbeginners.
com/ lists/ list-comprehensions-in-python/ , to additional information about of
list comprehension in python.

In [41]:
f= [0, 12, 45.21, 34, 99.91]
print(f)
Faren = np.array(f)
print("Respuesta\n",5*Faren/9 - 5*32/9)

[0, 12, 45.21, 34, 99.91]
Respuesta
 [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Write a Python program to find the set difference of two arrays. The set difference will
return the sorted, unique values in array1 that are not in array2. Expected Output:
Array1: [ 0 10 20 40 60 80]
Array2: [10, 30, 40, 50, 70, 90]
Set difference between two arrays: [ 0 20 60 80]
Hint:explore the use of function np.setdiff1d

In [42]:
a = np.array([0, 10, 20, 40, 60, 80])
print(a)
b = [10, 30, 40, 50, 70]
print(b)
print("Respuesta\n",np.setdiff1d(a, b))

[ 0 10 20 40 60 80]
[10, 30, 40, 50, 70]
Respuesta
 [ 0 20 60 80]


Write a Python program to create a 2-D array whose diagonal equals [4, 5, 6, 8] and 0’s
elsewhere.


In [43]:
a =  np.diagflat([4, 5, 6, 8])
print("Respuesta\n",a)

Respuesta
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 8]]
